name: profilometry
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - numpy
  - scipy
  - jupyter
  - matplotlib
  - h5py
  - pandas
  - pip:
      - prysm # Python package for optical metrology